name: Notify Microsoft 365

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Microsoft 365
        run: |
          curl -H "Content-Type: application/json" -d "{'text':'커밋이 발생했습니다. by gyueunnim'}" https://o365kopo.webhook.office.com/webhookb2/7bfe4d1f-d041-4708-b64a-be6d49f884a4@ad21525c-fc0f-4dbc-a403-67ce00add0e4/IncomingWebhook/bf106be5c5804d36a124c6a27807454e/60bd78a8-d56b-479c-a3ce-1345a15dc0ec
