name: Notify Microsoft 365

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Microsoft 365
        run: |
          curl -H "Content-Type: application/json" -d "{'text':'커밋이 발생했습니다. by gyueunnim token 적용'}" ${{secret.M365_WEBHOOK_URL}}
